# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5_W8ncIddUUdbQJPSyCohRM_JJrampZ

series 1
"""

import random
a= []
for i in range (10):
  num = random.randint(1,100)
  a.append(num)
sum1=sum (a)
print (a)
print (sum1)

"""series2"""

import random
a= []
n=1
for _ in range (10):
  num = random.randint(1,100)
  a.append(num)
  n*=num
print (a)
print (n)

"""series3"""

import random
a= []
n=1
for _ in range (10):
  num = random.randint(1,100)
  a.append(num)
  n+=num
  n=n/10
print (a)
print (n)

"""series4"""

n= int (input("введиет число "))
narr =[]
sum1 =0
n1=1
import random
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)
  sum1= sum(narr)
  n1*=a
print(narr)
print(sum1)
print(n1)

"""series5"""

n= int (input("введите число "))
narr =[]
sum1 =0
import random
for i in range(n):
  a= random.uniform(1, 100)
  narr.append(a)
  it= [int(x) for x in narr]
  sum1= sum(it)

print(narr)
print(sum1)
print(it)

"""series 6"""

n= int (input("введите число "))
narr =[]
sum1 =0
import random
for i in range(n):
  a= random.uniform(1, 100)
  narr.append(a)
  it= [num - int(num) for x in narr]
  sum1= sum(it)

print(narr)
print(sum1)
print(it)

"""series 7"""

n= int (input("введите число "))
narr =[]
sum1 =0
import random
for i in range(n):
  a= random.uniform(1, 100)
  narr.append(a)
  it= [round(num) for num in narr]
  sum1= sum(it)

print(narr)
print(sum1)
print(it)

"""series 8"""

n= int (input("введите число "))
narr =[]
for i in range(n):
  a= int (input ("введите число"))
  narr.append(a)
for a in narr:
  if a %2==0:
    print(a, end="")
    s+=1
print()
print(s)

"""series9"""

n= int (input("введите число "))
narr =[]
import random
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)
for i in range(n):
  if narr %2!=0:
    print(i+1, end="")
    s+=1
print()
print(s)

"""series 10"""

n= int (input("введите число "))
narr =[]
import random
for i in range(n):
  a= random.randint(-100, 100)
  narr.append(a)
  print(narr)
for a in narr:
  if a>0:
    print(i+1, end="")
    s+=1
if s>0:
  print ("true")
else:
  print("false")

"""series 11"""

n= int (input("введите число "))
s= int (input("введите число "))
c=0
narr =[]
import random
for i in range(n):
  a= random.randint(-100, 100)
  narr.append(a)
  print(narr)

for a in narr:
  if a<s:
    c+=1
if c>0:
  print ("true")
else:
  print("false")

"""series12"""

c=0
narr =[]
import random
while True:
  a= random.randint(-100, 100)
  if a==0:
    break
  print(a, end="")
  c+=1
print(c)

"""series 13"""

c=0
narr =[]
import random
while True:
  a= random.randint(-100, 100)
  if a==0:
    break
  print(a, end="")
  if a>0 and a%2==0:
    c+=a
print(c)

"""series14"""

c=int(input("введите число"))
s=0
narr =[]
import random
while True:
  a= random.randint(-100, 100)
  if a==0:
    break
  print(a, end="")
  c+=1
print(c)

"""series 15"""



"""series 16"""

import random
n= int (input("введите число "))
c=random.randint(1, 10)
narr =[]
u=0
for i in range(c):
  a= random.randint(-100, 100)
  narr.append(a)
  print(narr)
for i in range(c):
  if narr[1]>n:
    u=i+1
print (u)

"""series17"""

import random
n= int (input("введите число "))
narr =[]
u=0
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)
  narr.sort()
  print(narr)
b=random.randint(1,100)
print (b)
narr.append(b)
narr.sort()
print (narr)

"""series18"""

import random
n= int (input("введите число "))
narr =[]
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)
narr.sort()
print(narr)
for i in range(n):
  if i==0 or narr[i] !=narr[i-1]:

print (narr[i])

"""series19"""

import random
n= int (input("введите число "))
narr =[]
u=0
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)

print(narr)
for i in range(1, n):
  if narr[i]< narr[i-1]:
    print (narr[i])
    u+=1
print()
print (u)

"""series20"""

import random
n= int (input("введите число "))
narr =[]
u=0
for i in range(n):
  a= random.randint(1, 100)
  narr.append(a)
print(narr)
for i in range(n-1):
  if narr[i]< narr[i+1]:
    print (narr[i])
    u+=1
print ()
print (u)